# Generated by Django 3.1.14 on 2023-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='multiple_option',
            field=models.BooleanField(default=False, help_text='Permite selecición multiple', verbose_name='selección multiple'),
        ),
    ]
