# Generated by Django 4.1.5 on 2023-05-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name_plural': 'Zonas'},
        ),
    ]
