# Generated by Django 4.1.5 on 2023-06-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.questions')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.options')),
            ],
        ),
    ]
