# Generated by Django 4.1.5 on 2023-06-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='answer',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.zones'),
        ),
    ]
