# Generated by Django 4.1.5 on 2024-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questions_multiple_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='eps',
            field=models.CharField(choices=[('EPS002', 'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A.'), ('EPS008', 'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR'), ('EPS017', 'EPS FAMISANAR S.A.S.'), ('EPS037', 'NUEVA EPS S.A.'), ('EPS041', 'NUEVA EPS S.A. -CM'), ('EPS005', 'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S.'), ('EPSC34', 'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN SUBSIDIADO SAS "CAPITAL SALUD EPS-S S.A.S." -CM'), ('CCFC55', 'CAJACOPI EPS S.A.S -CM'), ('EPS010', 'EPS SURAMERICANA S.A.'), ('EPSIC6', 'PIJAOS SALUD EPSI -CM'), ('ESSC24', 'COOSALUD EPS S.A. -CM'), ('EPS042', 'COOSALUD EPS S.A.'), ('EAS027', 'FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES'), ('EPSIC5', 'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI -CM')], default='', help_text='Codigo Eps del paciente', max_length=10, verbose_name='Eps'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
