# Generated by Django 4.1.5 on 2023-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_zones_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', help_text='Codigo enfermedad', max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(default='', help_text='Nombre enfermedad', max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
            ],
            options={
                'verbose_name_plural': 'Enfermedades',
            },
        ),
    ]
