# Generated by Django 4.1.5 on 2023-05-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nombre paciente', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(default='', help_text='Apellido del paciente', max_length=50, verbose_name='Last name')),
                ('type_document', models.IntegerField(choices=[(0, 'C.c'), (1, 'T.i'), (2, 'R.c'), (3, 'C.e')], default=0)),
                ('number_document', models.IntegerField(default=0, help_text='Número de documento', verbose_name='Number Document')),
                ('birth_date', models.DateField(help_text='Fecha nacimiento del paciente', verbose_name='Birth date')),
                ('age', models.IntegerField(default=0, help_text='Edad del paciente', verbose_name='Age')),
                ('eps', models.CharField(default='', help_text='Codigo Eps del paciente', max_length=10, verbose_name='Eps')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.zones')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
