# Generated by Django 4.1.5 on 2023-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='diseases',
            field=models.ManyToManyField(to='api.diseases'),
        ),
    ]
